namespace TentacionSana.Domain.Deliveries;
public enum DeliveryStatus { Scheduled, Assigned, InRoute, Delivered, Partial, Failed, Cancelled }
public enum PaymentMethod { Cash, Qr, Transfer }
public enum PaymentStatus { Registered, Confirmed, Voided, Refunded }
public sealed class Delivery
{
 private Delivery(){} public Guid Id{get;private set;}public Guid OrderId{get;private set;}public Guid? DriverUserId{get;private set;}public DeliveryStatus Status{get;private set;}public DateTimeOffset ScheduledAtUtc{get;private set;}public DateTimeOffset? CompletedAtUtc{get;private set;}public string? ReceiverName{get;private set;}public string? FailureReason{get;private set;}public int Version{get;private set;}public List<DeliveryLine> Lines{get;private set;}=[];public List<DeliveryStatusHistory> History{get;private set;}=[];
 public static Delivery Create(Guid order,Guid? driver,DateTimeOffset scheduled,IEnumerable<(Guid line,int saleQuantity,int replacementQuantity,int tastingQuantity)> lines,Guid user,DateTimeOffset now){var x=new Delivery{Id=Guid.NewGuid(),OrderId=order,DriverUserId=driver,Status=driver is null?DeliveryStatus.Scheduled:DeliveryStatus.Assigned,ScheduledAtUtc=scheduled,Version=1};foreach(var l in lines)x.Lines.Add(DeliveryLine.Create(x.Id,l.line,l.saleQuantity,l.replacementQuantity,l.tastingQuantity));if(x.Lines.Count==0)throw new ArgumentException("La entrega requiere líneas.");x.History.Add(DeliveryStatusHistory.Create(x.Id,DeliveryStatus.Scheduled,x.Status,"Entrega programada",user,now));return x;}
 public static Delivery CreateHistoricallyCompleted(Guid order,DateTimeOffset completedAt,string receiver,IEnumerable<(Guid line,int saleQuantity,int replacementQuantity,int tastingQuantity)> lines,Guid user)
 {
  if(string.IsNullOrWhiteSpace(receiver))throw new ArgumentException("La persona receptora es obligatoria.");
  var delivery=new Delivery{Id=Guid.NewGuid(),OrderId=order,Status=DeliveryStatus.Delivered,ScheduledAtUtc=completedAt,CompletedAtUtc=completedAt,ReceiverName=receiver.Trim(),Version=1};
  foreach(var line in lines){var deliveryLine=DeliveryLine.Create(delivery.Id,line.line,line.saleQuantity,line.replacementQuantity,line.tastingQuantity);deliveryLine.Deliver(deliveryLine.AssignedQuantity);delivery.Lines.Add(deliveryLine);}
  if(delivery.Lines.Count==0)throw new ArgumentException("La entrega requiere líneas.");
  delivery.History.Add(DeliveryStatusHistory.Create(delivery.Id,DeliveryStatus.Scheduled,DeliveryStatus.Delivered,"Pedido registrado como ya realizado.",user,completedAt));
  return delivery;
 }
 public static Delivery Create(Guid order,Guid? driver,DateTimeOffset scheduled,IEnumerable<(Guid line,int quantity)> lines,Guid user,DateTimeOffset now)=>Create(order,driver,scheduled,lines.Select(x=>(x.line,x.quantity,0,0)),user,now);
 public void Start(Guid user,DateTimeOffset now){Transition(DeliveryStatus.InRoute,"Ruta iniciada",user,now);}
 public void ReturnToAssigned(Guid user,DateTimeOffset now){if(Status!=DeliveryStatus.InRoute)throw new InvalidOperationException("Solo una entrega en reparto puede volver a pendiente de salida.");Transition(DeliveryStatus.Assigned,"Salida de ruta revertida",user,now);}
 public void Assign(Guid driver,string reason,Guid user,DateTimeOffset now){if(driver==Guid.Empty)throw new ArgumentException("El repartidor es obligatorio.");if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("El motivo de asignación es obligatorio.");if(Status is DeliveryStatus.Delivered or DeliveryStatus.Cancelled)throw new InvalidOperationException("La entrega ya no admite asignación.");var old=Status;DriverUserId=driver;Status=DeliveryStatus.Assigned;Version++;History.Add(DeliveryStatusHistory.Create(Id,old,Status,reason,user,now));}
 public void Cancel(string reason,Guid user,DateTimeOffset now){if(Status==DeliveryStatus.Cancelled)return;if(Status==DeliveryStatus.Delivered)throw new InvalidOperationException("Una entrega completada no puede cancelarse.");if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("El motivo es obligatorio.");Transition(DeliveryStatus.Cancelled,reason,user,now);}
 public void Complete(IReadOnlyDictionary<Guid,int> quantities,string receiver,Guid user,DateTimeOffset now){var detailed=Lines.ToDictionary(x=>x.Id,x=>{var quantity=quantities.GetValueOrDefault(x.Id);var sale=Math.Min(quantity,x.PendingSaleQuantity);var remaining=quantity-sale;var replacement=Math.Min(remaining,x.PendingReplacementQuantity);return (sale,replacement,remaining-replacement);});Complete(detailed,receiver,user,now);}
 public void Complete(IReadOnlyDictionary<Guid,(int SaleQuantity,int ReplacementQuantity,int TastingQuantity)> quantities,string receiver,Guid user,DateTimeOffset now){if(Status is not (DeliveryStatus.Assigned or DeliveryStatus.InRoute or DeliveryStatus.Partial))throw new InvalidOperationException("La entrega no puede confirmarse en su estado actual.");if(string.IsNullOrWhiteSpace(receiver))throw new ArgumentException("La persona receptora es obligatoria.");foreach(var line in Lines){var q=quantities.GetValueOrDefault(line.Id);line.Deliver(q.SaleQuantity,q.ReplacementQuantity,q.TastingQuantity);}ReceiverName=receiver.Trim();CompletedAtUtc=now;var next=Lines.All(x=>x.PendingQuantity==0)?DeliveryStatus.Delivered:DeliveryStatus.Partial;Transition(next,"Cantidades entregadas confirmadas",user,now);}
 public void Fail(string reason,Guid user,DateTimeOffset now){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("El motivo es obligatorio.");FailureReason=reason.Trim();Transition(DeliveryStatus.Failed,reason,user,now);}
 private void Transition(DeliveryStatus next,string reason,Guid user,DateTimeOffset now){var old=Status;Status=next;Version++;History.Add(DeliveryStatusHistory.Create(Id,old,next,reason,user,now));}
}
public sealed class DeliveryLine{private DeliveryLine(){}public Guid Id{get;private set;}public Guid DeliveryId{get;private set;}public Guid OrderLineId{get;private set;}public int AssignedQuantity{get;private set;}public int AssignedSaleQuantity{get;private set;}public int AssignedReplacementQuantity{get;private set;}public int AssignedTastingQuantity{get;private set;}public int DeliveredQuantity{get;private set;}public int DeliveredSaleQuantity{get;private set;}public int DeliveredReplacementQuantity{get;private set;}public int DeliveredTastingQuantity{get;private set;}public int PendingQuantity=>AssignedQuantity-DeliveredQuantity;public int PendingSaleQuantity=>AssignedSaleQuantity-DeliveredSaleQuantity;public int PendingReplacementQuantity=>AssignedReplacementQuantity-DeliveredReplacementQuantity;public int PendingTastingQuantity=>AssignedTastingQuantity-DeliveredTastingQuantity;internal static DeliveryLine Create(Guid delivery,Guid line,int saleQuantity,int replacementQuantity,int tastingQuantity){if(saleQuantity<0||replacementQuantity<0||tastingQuantity<0||saleQuantity+replacementQuantity+tastingQuantity<1)throw new ArgumentException("La cantidad asignada debe ser positiva.");return new(){Id=Guid.NewGuid(),DeliveryId=delivery,OrderLineId=line,AssignedQuantity=saleQuantity+replacementQuantity+tastingQuantity,AssignedSaleQuantity=saleQuantity,AssignedReplacementQuantity=replacementQuantity,AssignedTastingQuantity=tastingQuantity};}internal void Deliver(int quantity){if(quantity<0||quantity>PendingQuantity)throw new ArgumentException("La cantidad entregada supera la pendiente.");var sale=Math.Min(quantity,PendingSaleQuantity);var left=quantity-sale;var replacement=Math.Min(left,PendingReplacementQuantity);Deliver(sale,replacement,left-replacement);}internal void Deliver(int saleQuantity,int replacementQuantity,int tastingQuantity){if(saleQuantity<0||replacementQuantity<0||tastingQuantity<0||saleQuantity>PendingSaleQuantity||replacementQuantity>PendingReplacementQuantity||tastingQuantity>PendingTastingQuantity)throw new ArgumentException("La cantidad entregada supera la pendiente.");DeliveredSaleQuantity+=saleQuantity;DeliveredReplacementQuantity+=replacementQuantity;DeliveredTastingQuantity+=tastingQuantity;DeliveredQuantity+=saleQuantity+replacementQuantity+tastingQuantity;}}
public sealed class DeliveryStatusHistory{private DeliveryStatusHistory(){}public Guid Id{get;private set;}public Guid DeliveryId{get;private set;}public DeliveryStatus PreviousStatus{get;private set;}public DeliveryStatus NewStatus{get;private set;}public string Reason{get;private set;}="";public Guid UserId{get;private set;}public DateTimeOffset ChangedAtUtc{get;private set;}internal static DeliveryStatusHistory Create(Guid delivery,DeliveryStatus old,DeliveryStatus next,string reason,Guid user,DateTimeOffset now)=>new(){Id=Guid.NewGuid(),DeliveryId=delivery,PreviousStatus=old,NewStatus=next,Reason=reason,UserId=user,ChangedAtUtc=now};}
public sealed class Sale{private Sale(){}public Guid Id{get;private set;}public Guid OrderId{get;private set;}public Guid DeliveryId{get;private set;}public decimal Amount{get;private set;}public decimal? HistoricalCost{get;private set;}public DateTimeOffset OccurredAtUtc{get;private set;}public static Sale Create(Guid order,Guid delivery,decimal amount,decimal? cost,DateTimeOffset now)=>new(){Id=Guid.NewGuid(),OrderId=order,DeliveryId=delivery,Amount=decimal.Round(amount,2),HistoricalCost=cost is null?null:decimal.Round(cost.Value,2),OccurredAtUtc=now};}
public sealed class Payment{private Payment(){}public Guid Id{get;private set;}public Guid OrderId{get;private set;}public Guid? DeliveryId{get;private set;}public Guid ResponsiblePartyId{get;private set;}public decimal Amount{get;private set;}public PaymentMethod Method{get;private set;}public PaymentStatus Status{get;private set;}public Guid ReceivedByUserId{get;private set;}public string? ExternalReference{get;private set;}public string? Notes{get;private set;}public DateTimeOffset PaymentDateUtc{get;private set;}public DateTimeOffset ReceivedAtUtc{get;private set;}public static Payment Create(Guid order,Guid? delivery,decimal amount,PaymentMethod method,Guid receiver,string? reference,DateTimeOffset now,string? notes=null,DateTimeOffset? paymentDate=null,Guid? responsiblePartyId=null){if(amount<=0)throw new ArgumentException("El pago debe ser positivo.");return new(){Id=Guid.NewGuid(),OrderId=order,DeliveryId=delivery,ResponsiblePartyId=responsiblePartyId??Guid.Empty,Amount=decimal.Round(amount,2),Method=method,Status=PaymentStatus.Confirmed,ReceivedByUserId=receiver,ExternalReference=string.IsNullOrWhiteSpace(reference)?null:reference.Trim(),Notes=string.IsNullOrWhiteSpace(notes)?null:notes.Trim(),PaymentDateUtc=paymentDate??now,ReceivedAtUtc=now};}}
public sealed class PaymentAllocation{private PaymentAllocation(){}public Guid Id{get;private set;}public Guid PaymentId{get;private set;}public Guid OrderId{get;private set;}public decimal Amount{get;private set;}public int ApplicationOrder{get;private set;}public DateTimeOffset AppliedAtUtc{get;private set;}public static PaymentAllocation Create(Guid paymentId,Guid orderId,decimal amount,int applicationOrder,DateTimeOffset now){if(paymentId==Guid.Empty||orderId==Guid.Empty)throw new ArgumentException("El pago y el pedido son obligatorios.");if(amount<=0)throw new ArgumentException("La aplicaciÃ³n del pago debe ser positiva.");return new(){Id=Guid.NewGuid(),PaymentId=paymentId,OrderId=orderId,Amount=decimal.Round(amount,2),ApplicationOrder=applicationOrder,AppliedAtUtc=now};}}
public sealed class PaymentEvidence{private PaymentEvidence(){}public Guid Id{get;private set;}public Guid PaymentId{get;private set;}public string PublicId{get;private set;}="";public string FileName{get;private set;}="";public string Format{get;private set;}="";public long Bytes{get;private set;}public Guid UploadedByUserId{get;private set;}public DateTimeOffset UploadedAtUtc{get;private set;}public static PaymentEvidence Create(Guid paymentId,string publicId,string fileName,string format,long bytes,Guid userId,DateTimeOffset now){if(string.IsNullOrWhiteSpace(publicId))throw new ArgumentException("La evidencia del pago es obligatoria.");return new(){Id=Guid.NewGuid(),PaymentId=paymentId,PublicId=publicId,FileName=fileName,Format=format,Bytes=bytes,UploadedByUserId=userId,UploadedAtUtc=now};}}
public sealed class Receivable{private Receivable(){}public Guid OrderId{get;private set;}public Guid CustomerId{get;private set;}public Guid? PayerId{get;private set;}public decimal InvoicedAmount{get;private set;}public decimal PaidAmount{get;private set;}public decimal Balance=>Math.Max(0,InvoicedAmount-PaidAmount);public decimal CreditAmount=>Math.Max(0,PaidAmount-InvoicedAmount);public int Version{get;private set;}public static Receivable Create(Guid order,Guid customer,Guid? payer)=>new(){OrderId=order,CustomerId=customer,PayerId=payer,Version=1};public void AddSale(decimal amount){if(amount<=0)throw new ArgumentException("La venta debe ser positiva.");InvoicedAmount+=amount;Version++;}public void ApplyPayment(decimal amount,bool allowAdvance=false){if(amount<=0)throw new InvalidOperationException("El pago debe ser positivo.");if(!allowAdvance&&amount>Balance)throw new InvalidOperationException("El pago supera el saldo exigible.");PaidAmount+=amount;Version++;}}
