using TentacionSana.Domain.Deliveries;
namespace TentacionSana.UnitTests.Deliveries;
public sealed class DeliveryTests
{
 [Fact]public void PartialDeliveryKeepsPendingQuantity(){var line=Guid.NewGuid();var d=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(line,5)],Guid.NewGuid(),DateTimeOffset.UtcNow);d.Complete(new Dictionary<Guid,int>{{d.Lines[0].Id,2}},"Ana",Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Equal(DeliveryStatus.Partial,d.Status);Assert.Equal(3,d.Lines[0].PendingQuantity);}
 [Fact]public void CompleteDeliveryRequiresReceiver(){var d=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(Guid.NewGuid(),1)],Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Throws<ArgumentException>(()=>d.Complete(new Dictionary<Guid,int>{{d.Lines[0].Id,1}},"",Guid.NewGuid(),DateTimeOffset.UtcNow));}
 [Fact]public void PaymentCannotBeZero(){Assert.Throws<ArgumentException>(()=>Payment.Create(Guid.NewGuid(),null,0,PaymentMethod.Cash,Guid.NewGuid(),null,DateTimeOffset.UtcNow));}
 [Fact]public void PaymentAllocationKeepsAppliedOrderAndSequence(){var paymentId=Guid.NewGuid();var orderId=Guid.NewGuid();var at=DateTimeOffset.UtcNow;var allocation=PaymentAllocation.Create(paymentId,orderId,25.456m,2,at);Assert.Equal(paymentId,allocation.PaymentId);Assert.Equal(orderId,allocation.OrderId);Assert.Equal(25.46m,allocation.Amount);Assert.Equal(2,allocation.ApplicationOrder);}
 [Fact]public void AccountStatementAuditKeepsOrderSnapshot(){var orderId=Guid.NewGuid();var report=AccountStatementReport.Create("EC-CLIENTE-20261004-001",Guid.NewGuid(),Guid.NewGuid(),AccountStatementReportType.Current,80,100,20,true,true,true,DateTimeOffset.UtcNow,[(orderId,100m,20m,80m)]);var included=Assert.Single(report.Orders);Assert.Equal(orderId,included.OrderId);Assert.Equal(80m,report.BalanceAtGeneration);Assert.Equal(100m,report.PreviousBalance);Assert.Equal(20m,report.RegisteredPayment);}
 [Fact]public void ReceivableRejectsOverpayment(){var r=Receivable.Create(Guid.NewGuid(),Guid.NewGuid(),null);r.AddSale(20);Assert.Throws<InvalidOperationException>(()=>r.ApplyPayment(21));}
 [Fact]public void AssignmentIsTrackedAndIncrementsVersion(){var user=Guid.NewGuid();var d=Delivery.Create(Guid.NewGuid(),null,DateTimeOffset.UtcNow,[(Guid.NewGuid(),1)],user,DateTimeOffset.UtcNow);var driver=Guid.NewGuid();d.Assign(driver,"Asignación inicial",user,DateTimeOffset.UtcNow);Assert.Equal(driver,d.DriverUserId);Assert.Equal(DeliveryStatus.Assigned,d.Status);Assert.Equal(2,d.Version);Assert.Equal("Asignación inicial",d.History[^1].Reason);}
 [Fact]public void AssignmentRequiresReason(){var d=Delivery.Create(Guid.NewGuid(),null,DateTimeOffset.UtcNow,[(Guid.NewGuid(),1)],Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Throws<ArgumentException>(()=>d.Assign(Guid.NewGuid(),"",Guid.NewGuid(),DateTimeOffset.UtcNow));}
 [Fact]public void DeliveryCannotExceedItsPendingQuantity(){var d=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(Guid.NewGuid(),2)],Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Throws<ArgumentException>(()=>d.Complete(new Dictionary<Guid,int>{{d.Lines[0].Id,3}},"Ana",Guid.NewGuid(),DateTimeOffset.UtcNow));}
 [Fact]public void HistoricalCompletedDeliveryKeepsAllDeliveryKinds(){var line=Guid.NewGuid();var d=Delivery.CreateHistoricallyCompleted(Guid.NewGuid(),DateTimeOffset.UtcNow,"María",[(line,10,2,1)],Guid.NewGuid());var delivered=Assert.Single(d.Lines);Assert.Equal(DeliveryStatus.Delivered,d.Status);Assert.Equal(13,delivered.DeliveredQuantity);Assert.Equal(10,delivered.DeliveredSaleQuantity);Assert.Equal(2,delivered.DeliveredReplacementQuantity);Assert.Equal(1,delivered.DeliveredTastingQuantity);}
 [Fact]public void EvidenceKeepsOnlySafeBaseFileName(){var evidence=DeliveryEvidence.Create(Guid.NewGuid(),"private/id","../photo.jpg","jpg",10,Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Equal("photo.jpg",evidence.FileName);Assert.True(evidence.IsActive);}
 [Fact]public void AdvancePaymentBecomesCreditAndIsConsumedBySale(){var r=Receivable.Create(Guid.NewGuid(),Guid.NewGuid(),null);r.ApplyPayment(10,true);Assert.Equal(10,r.CreditAmount);Assert.Equal(0,r.Balance);r.AddSale(25);Assert.Equal(0,r.CreditAmount);Assert.Equal(15,r.Balance);}
 [Fact]public void DetailedDeliveryKeepsSaleReplacementAndTastingSeparated(){var line=Guid.NewGuid();var d=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(line,5,2,1)],Guid.NewGuid(),DateTimeOffset.UtcNow);d.Complete(new Dictionary<Guid,(int SaleQuantity,int ReplacementQuantity,int TastingQuantity)>{{d.Lines[0].Id,(3,1,1)}},"Ana",Guid.NewGuid(),DateTimeOffset.UtcNow);var delivered=Assert.Single(d.Lines);Assert.Equal(3,delivered.DeliveredSaleQuantity);Assert.Equal(1,delivered.DeliveredReplacementQuantity);Assert.Equal(1,delivered.DeliveredTastingQuantity);Assert.Equal(3,delivered.PendingQuantity);}
 [Fact]public void DriverCanReorderRouteAfterItStarts(){var first=Guid.NewGuid();var second=Guid.NewGuid();var route=DeliveryRoute.Create(Guid.NewGuid(),DateTimeOffset.UtcNow,[first,second],Guid.NewGuid(),DateTimeOffset.UtcNow);route.Start(DateTimeOffset.UtcNow);route.Reorder([second,first]);Assert.Equal(second,route.Stops.Single(x=>x.Position==1).DeliveryId);route.Complete(DateTimeOffset.UtcNow);Assert.Throws<InvalidOperationException>(()=>route.Reorder([first,second]));}
 [Fact]public void RemovingAStopKeepsRemainingRoutePositionsContiguous(){var first=Guid.NewGuid();var second=Guid.NewGuid();var third=Guid.NewGuid();var route=DeliveryRoute.Create(Guid.NewGuid(),DateTimeOffset.UtcNow,[first,second,third],Guid.NewGuid(),DateTimeOffset.UtcNow);route.RemoveStop(second);Assert.Equal([first,third],route.Stops.OrderBy(x=>x.Position).Select(x=>x.DeliveryId));Assert.Equal([1,2],route.Stops.OrderBy(x=>x.Position).Select(x=>x.Position));}
 [Fact]public void DeliveryInRouteCanReturnToAssigned(){var user=Guid.NewGuid();var delivery=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(Guid.NewGuid(),1)],user,DateTimeOffset.UtcNow);delivery.Start(user,DateTimeOffset.UtcNow);delivery.ReturnToAssigned(user,DateTimeOffset.UtcNow);Assert.Equal(DeliveryStatus.Assigned,delivery.Status);Assert.Equal("Salida de ruta revertida",delivery.History[^1].Reason);}
 [Fact]public void CancellingAnOrderCanCancelItsPendingDelivery(){var user=Guid.NewGuid();var delivery=Delivery.Create(Guid.NewGuid(),Guid.NewGuid(),DateTimeOffset.UtcNow,[(Guid.NewGuid(),1)],user,DateTimeOffset.UtcNow);delivery.Cancel("Pedido cancelado",user,DateTimeOffset.UtcNow);Assert.Equal(DeliveryStatus.Cancelled,delivery.Status);Assert.Equal("Pedido cancelado",delivery.History[^1].Reason);}
}
